# Generated by Django 3.1.4 on 2021-03-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Title', models.CharField(max_length=500)),
                ('URL', models.CharField(max_length=500)),
                ('Date_time', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=500)),
            ],
        ),
    ]
